answer_paths:
  cases/eval_2-5-333.yaml:
  - eval_2-5-333_0.txt
  - eval_2-5-333_1.txt
  - eval_2-5-333_2.txt
  - eval_2-5-333_3.txt
  - eval_2-5-333_4.txt
  - eval_2-5-333_5.txt
  - eval_2-5-333_6.txt
  - eval_2-5-333_7.txt
  - eval_2-5-333_8.txt
  - eval_2-5-333_9.txt
  cases/eval_2-5-334.yaml:
  - eval_2-5-334_0.txt
  - eval_2-5-334_1.txt
  - eval_2-5-334_2.txt
  - eval_2-5-334_3.txt
  - eval_2-5-334_4.txt
  - eval_2-5-334_5.txt
  - eval_2-5-334_6.txt
  - eval_2-5-334_7.txt
  - eval_2-5-334_8.txt
  - eval_2-5-334_9.txt
  cases/eval_2-5-336.yaml:
  - eval_2-5-336_0.txt
  - eval_2-5-336_1.txt
  - eval_2-5-336_2.txt
  - eval_2-5-336_3.txt
  - eval_2-5-336_4.txt
  - eval_2-5-336_5.txt
  - eval_2-5-336_6.txt
  - eval_2-5-336_7.txt
  - eval_2-5-336_8.txt
  - eval_2-5-336_9.txt
  cases/eval_2-5-338.yaml:
  - eval_2-5-338_0.txt
  - eval_2-5-338_1.txt
  - eval_2-5-338_2.txt
  - eval_2-5-338_3.txt
  - eval_2-5-338_4.txt
  - eval_2-5-338_5.txt
  - eval_2-5-338_6.txt
  - eval_2-5-338_7.txt
  - eval_2-5-338_8.txt
  - eval_2-5-338_9.txt
  cases/eval_2-5-341.yaml:
  - eval_2-5-341_0.txt
  - eval_2-5-341_1.txt
  - eval_2-5-341_2.txt
  - eval_2-5-341_3.txt
  - eval_2-5-341_4.txt
  - eval_2-5-341_5.txt
  - eval_2-5-341_6.txt
  - eval_2-5-341_7.txt
  - eval_2-5-341_8.txt
  - eval_2-5-341_9.txt
  cases/eval_2-5-345.yaml:
  - eval_2-5-345_0.txt
  - eval_2-5-345_1.txt
  - eval_2-5-345_2.txt
  - eval_2-5-345_3.txt
  - eval_2-5-345_4.txt
  - eval_2-5-345_5.txt
  - eval_2-5-345_6.txt
  - eval_2-5-345_7.txt
  - eval_2-5-345_8.txt
  - eval_2-5-345_9.txt
  cases/eval_2-5-346.yaml:
  - eval_2-5-346_0.txt
  - eval_2-5-346_1.txt
  - eval_2-5-346_2.txt
  - eval_2-5-346_3.txt
  - eval_2-5-346_4.txt
  - eval_2-5-346_5.txt
  - eval_2-5-346_6.txt
  - eval_2-5-346_7.txt
  - eval_2-5-346_8.txt
  - eval_2-5-346_9.txt
  cases/eval_2-5-348.yaml:
  - eval_2-5-348_0.txt
  - eval_2-5-348_1.txt
  - eval_2-5-348_2.txt
  - eval_2-5-348_3.txt
  - eval_2-5-348_4.txt
  - eval_2-5-348_5.txt
  - eval_2-5-348_6.txt
  - eval_2-5-348_7.txt
  - eval_2-5-348_8.txt
  - eval_2-5-348_9.txt
  cases/eval_2-5-352.yaml:
  - eval_2-5-352_0.txt
  - eval_2-5-352_1.txt
  - eval_2-5-352_2.txt
  - eval_2-5-352_3.txt
  - eval_2-5-352_4.txt
  - eval_2-5-352_5.txt
  - eval_2-5-352_6.txt
  - eval_2-5-352_7.txt
  - eval_2-5-352_8.txt
  - eval_2-5-352_9.txt
  cases/eval_2-5-357.yaml:
  - eval_2-5-357_0.txt
  - eval_2-5-357_1.txt
  - eval_2-5-357_2.txt
  - eval_2-5-357_3.txt
  - eval_2-5-357_4.txt
  - eval_2-5-357_5.txt
  - eval_2-5-357_6.txt
  - eval_2-5-357_7.txt
  - eval_2-5-357_8.txt
  - eval_2-5-357_9.txt
  cases/eval_2-5-362.yaml:
  - eval_2-5-362_0.txt
  - eval_2-5-362_1.txt
  - eval_2-5-362_2.txt
  - eval_2-5-362_3.txt
  - eval_2-5-362_4.txt
  - eval_2-5-362_5.txt
  - eval_2-5-362_6.txt
  - eval_2-5-362_7.txt
  - eval_2-5-362_8.txt
  - eval_2-5-362_9.txt
  cases/eval_2-5-364.yaml:
  - eval_2-5-364_0.txt
  - eval_2-5-364_1.txt
  - eval_2-5-364_2.txt
  - eval_2-5-364_3.txt
  - eval_2-5-364_4.txt
  - eval_2-5-364_5.txt
  - eval_2-5-364_6.txt
  - eval_2-5-364_7.txt
  - eval_2-5-364_8.txt
  - eval_2-5-364_9.txt
  cases/eval_2-5-368.yaml:
  - eval_2-5-368_0.txt
  - eval_2-5-368_1.txt
  - eval_2-5-368_2.txt
  - eval_2-5-368_3.txt
  - eval_2-5-368_4.txt
  - eval_2-5-368_5.txt
  - eval_2-5-368_6.txt
  - eval_2-5-368_7.txt
  - eval_2-5-368_8.txt
  - eval_2-5-368_9.txt
  cases/eval_2-5-372.yaml:
  - eval_2-5-372_0.txt
  - eval_2-5-372_1.txt
  - eval_2-5-372_2.txt
  - eval_2-5-372_3.txt
  - eval_2-5-372_4.txt
  - eval_2-5-372_5.txt
  - eval_2-5-372_6.txt
  - eval_2-5-372_7.txt
  - eval_2-5-372_8.txt
  - eval_2-5-372_9.txt
  cases/eval_2-5-376.yaml:
  - eval_2-5-376_0.txt
  - eval_2-5-376_1.txt
  - eval_2-5-376_2.txt
  - eval_2-5-376_3.txt
  - eval_2-5-376_4.txt
  - eval_2-5-376_5.txt
  - eval_2-5-376_6.txt
  - eval_2-5-376_7.txt
  - eval_2-5-376_8.txt
  - eval_2-5-376_9.txt
  cases/eval_2-5-377.yaml:
  - eval_2-5-377_0.txt
  - eval_2-5-377_1.txt
  - eval_2-5-377_2.txt
  - eval_2-5-377_3.txt
  - eval_2-5-377_4.txt
  - eval_2-5-377_5.txt
  - eval_2-5-377_6.txt
  - eval_2-5-377_7.txt
  - eval_2-5-377_8.txt
  - eval_2-5-377_9.txt
  cases/eval_2-5-379.yaml:
  - eval_2-5-379_0.txt
  - eval_2-5-379_1.txt
  - eval_2-5-379_2.txt
  - eval_2-5-379_3.txt
  - eval_2-5-379_4.txt
  - eval_2-5-379_5.txt
  - eval_2-5-379_6.txt
  - eval_2-5-379_7.txt
  - eval_2-5-379_8.txt
  - eval_2-5-379_9.txt
  cases/eval_2-5-380.yaml:
  - eval_2-5-380_0.txt
  - eval_2-5-380_1.txt
  - eval_2-5-380_2.txt
  - eval_2-5-380_3.txt
  - eval_2-5-380_4.txt
  - eval_2-5-380_5.txt
  - eval_2-5-380_6.txt
  - eval_2-5-380_7.txt
  - eval_2-5-380_8.txt
  - eval_2-5-380_9.txt
  cases/eval_2-6-387.yaml:
  - eval_2-6-387_0.txt
  - eval_2-6-387_1.txt
  - eval_2-6-387_2.txt
  - eval_2-6-387_3.txt
  - eval_2-6-387_4.txt
  - eval_2-6-387_5.txt
  - eval_2-6-387_6.txt
  - eval_2-6-387_7.txt
  - eval_2-6-387_8.txt
  - eval_2-6-387_9.txt
  cases/eval_2-6-388.yaml:
  - eval_2-6-388_0.txt
  - eval_2-6-388_1.txt
  - eval_2-6-388_2.txt
  - eval_2-6-388_3.txt
  - eval_2-6-388_4.txt
  - eval_2-6-388_5.txt
  - eval_2-6-388_6.txt
  - eval_2-6-388_7.txt
  - eval_2-6-388_8.txt
  - eval_2-6-388_9.txt
  cases/eval_2-6-392.yaml:
  - eval_2-6-392_0.txt
  - eval_2-6-392_1.txt
  - eval_2-6-392_2.txt
  - eval_2-6-392_3.txt
  - eval_2-6-392_4.txt
  - eval_2-6-392_5.txt
  - eval_2-6-392_6.txt
  - eval_2-6-392_7.txt
  - eval_2-6-392_8.txt
  - eval_2-6-392_9.txt
  cases/eval_2-6-393.yaml:
  - eval_2-6-393_0.txt
  - eval_2-6-393_1.txt
  - eval_2-6-393_2.txt
  - eval_2-6-393_3.txt
  - eval_2-6-393_4.txt
  - eval_2-6-393_5.txt
  - eval_2-6-393_6.txt
  - eval_2-6-393_7.txt
  - eval_2-6-393_8.txt
  - eval_2-6-393_9.txt
  cases/eval_2-6-394.yaml:
  - eval_2-6-394_0.txt
  - eval_2-6-394_1.txt
  - eval_2-6-394_2.txt
  - eval_2-6-394_3.txt
  - eval_2-6-394_4.txt
  - eval_2-6-394_5.txt
  - eval_2-6-394_6.txt
  - eval_2-6-394_7.txt
  - eval_2-6-394_8.txt
  - eval_2-6-394_9.txt
  cases/eval_2-6-396.yaml:
  - eval_2-6-396_0.txt
  - eval_2-6-396_1.txt
  - eval_2-6-396_2.txt
  - eval_2-6-396_3.txt
  - eval_2-6-396_4.txt
  - eval_2-6-396_5.txt
  - eval_2-6-396_6.txt
  - eval_2-6-396_7.txt
  - eval_2-6-396_8.txt
  - eval_2-6-396_9.txt
  cases/eval_2-6-398.yaml:
  - eval_2-6-398_0.txt
  - eval_2-6-398_1.txt
  - eval_2-6-398_2.txt
  - eval_2-6-398_3.txt
  - eval_2-6-398_4.txt
  - eval_2-6-398_5.txt
  - eval_2-6-398_6.txt
  - eval_2-6-398_7.txt
  - eval_2-6-398_8.txt
  - eval_2-6-398_9.txt
  cases/eval_2-6-401.yaml:
  - eval_2-6-401_0.txt
  - eval_2-6-401_1.txt
  - eval_2-6-401_2.txt
  - eval_2-6-401_3.txt
  - eval_2-6-401_4.txt
  - eval_2-6-401_5.txt
  - eval_2-6-401_6.txt
  - eval_2-6-401_7.txt
  - eval_2-6-401_8.txt
  - eval_2-6-401_9.txt
  cases/eval_2-6-403.yaml:
  - eval_2-6-403_0.txt
  - eval_2-6-403_1.txt
  - eval_2-6-403_2.txt
  - eval_2-6-403_3.txt
  - eval_2-6-403_4.txt
  - eval_2-6-403_5.txt
  - eval_2-6-403_6.txt
  - eval_2-6-403_7.txt
  - eval_2-6-403_8.txt
  - eval_2-6-403_9.txt
  cases/eval_2-6-404.yaml:
  - eval_2-6-404_0.txt
  - eval_2-6-404_1.txt
  - eval_2-6-404_2.txt
  - eval_2-6-404_3.txt
  - eval_2-6-404_4.txt
  - eval_2-6-404_5.txt
  - eval_2-6-404_6.txt
  - eval_2-6-404_7.txt
  - eval_2-6-404_8.txt
  - eval_2-6-404_9.txt
  cases/eval_2-6-406.yaml:
  - eval_2-6-406_0.txt
  - eval_2-6-406_1.txt
  - eval_2-6-406_2.txt
  - eval_2-6-406_3.txt
  - eval_2-6-406_4.txt
  - eval_2-6-406_5.txt
  - eval_2-6-406_6.txt
  - eval_2-6-406_7.txt
  - eval_2-6-406_8.txt
  - eval_2-6-406_9.txt
  cases/eval_2-6-407.yaml:
  - eval_2-6-407_0.txt
  - eval_2-6-407_1.txt
  - eval_2-6-407_2.txt
  - eval_2-6-407_3.txt
  - eval_2-6-407_4.txt
  - eval_2-6-407_5.txt
  - eval_2-6-407_6.txt
  - eval_2-6-407_7.txt
  - eval_2-6-407_8.txt
  - eval_2-6-407_9.txt
  cases/eval_2-7-424.yaml:
  - eval_2-7-424_0.txt
  - eval_2-7-424_1.txt
  - eval_2-7-424_2.txt
  - eval_2-7-424_3.txt
  - eval_2-7-424_4.txt
  - eval_2-7-424_5.txt
  - eval_2-7-424_6.txt
  - eval_2-7-424_7.txt
  - eval_2-7-424_8.txt
  - eval_2-7-424_9.txt
  cases/eval_2-7-425.yaml:
  - eval_2-7-425_0.txt
  - eval_2-7-425_1.txt
  - eval_2-7-425_2.txt
  - eval_2-7-425_3.txt
  - eval_2-7-425_4.txt
  - eval_2-7-425_5.txt
  - eval_2-7-425_6.txt
  - eval_2-7-425_7.txt
  - eval_2-7-425_8.txt
  - eval_2-7-425_9.txt
  cases/eval_2-7-426.yaml:
  - eval_2-7-426_0.txt
  - eval_2-7-426_1.txt
  - eval_2-7-426_2.txt
  - eval_2-7-426_3.txt
  - eval_2-7-426_4.txt
  - eval_2-7-426_5.txt
  - eval_2-7-426_6.txt
  - eval_2-7-426_7.txt
  - eval_2-7-426_8.txt
  - eval_2-7-426_9.txt
  cases/eval_2-7-427.yaml:
  - eval_2-7-427_0.txt
  - eval_2-7-427_1.txt
  - eval_2-7-427_2.txt
  - eval_2-7-427_3.txt
  - eval_2-7-427_4.txt
  - eval_2-7-427_5.txt
  - eval_2-7-427_6.txt
  - eval_2-7-427_7.txt
  - eval_2-7-427_8.txt
  - eval_2-7-427_9.txt
  cases/eval_2-7-431.yaml:
  - eval_2-7-431_0.txt
  - eval_2-7-431_1.txt
  - eval_2-7-431_2.txt
  - eval_2-7-431_3.txt
  - eval_2-7-431_4.txt
  - eval_2-7-431_5.txt
  - eval_2-7-431_6.txt
  - eval_2-7-431_7.txt
  - eval_2-7-431_8.txt
  - eval_2-7-431_9.txt
  cases/eval_2-7-432.yaml:
  - eval_2-7-432_0.txt
  - eval_2-7-432_1.txt
  - eval_2-7-432_2.txt
  - eval_2-7-432_3.txt
  - eval_2-7-432_4.txt
  - eval_2-7-432_5.txt
  - eval_2-7-432_6.txt
  - eval_2-7-432_7.txt
  - eval_2-7-432_8.txt
  - eval_2-7-432_9.txt
  cases/eval_2-7-434.yaml:
  - eval_2-7-434_0.txt
  - eval_2-7-434_1.txt
  - eval_2-7-434_2.txt
  - eval_2-7-434_3.txt
  - eval_2-7-434_4.txt
  - eval_2-7-434_5.txt
  - eval_2-7-434_6.txt
  - eval_2-7-434_7.txt
  - eval_2-7-434_8.txt
  - eval_2-7-434_9.txt
  cases/eval_2-7-436.yaml:
  - eval_2-7-436_0.txt
  - eval_2-7-436_1.txt
  - eval_2-7-436_2.txt
  - eval_2-7-436_3.txt
  - eval_2-7-436_4.txt
  - eval_2-7-436_5.txt
  - eval_2-7-436_6.txt
  - eval_2-7-436_7.txt
  - eval_2-7-436_8.txt
  - eval_2-7-436_9.txt
  cases/eval_2-7-438.yaml:
  - eval_2-7-438_0.txt
  - eval_2-7-438_1.txt
  - eval_2-7-438_2.txt
  - eval_2-7-438_3.txt
  - eval_2-7-438_4.txt
  - eval_2-7-438_5.txt
  - eval_2-7-438_6.txt
  - eval_2-7-438_7.txt
  - eval_2-7-438_8.txt
  - eval_2-7-438_9.txt
  cases/eval_2-7-439.yaml:
  - eval_2-7-439_0.txt
  - eval_2-7-439_1.txt
  - eval_2-7-439_2.txt
  - eval_2-7-439_3.txt
  - eval_2-7-439_4.txt
  - eval_2-7-439_5.txt
  - eval_2-7-439_6.txt
  - eval_2-7-439_7.txt
  - eval_2-7-439_8.txt
  - eval_2-7-439_9.txt
  cases/eval_2-8-450.yaml:
  - eval_2-8-450_0.txt
  - eval_2-8-450_1.txt
  - eval_2-8-450_2.txt
  - eval_2-8-450_3.txt
  - eval_2-8-450_4.txt
  - eval_2-8-450_5.txt
  - eval_2-8-450_6.txt
  - eval_2-8-450_7.txt
  - eval_2-8-450_8.txt
  - eval_2-8-450_9.txt
  cases/eval_2-8-451.yaml:
  - eval_2-8-451_0.txt
  - eval_2-8-451_1.txt
  - eval_2-8-451_2.txt
  - eval_2-8-451_3.txt
  - eval_2-8-451_4.txt
  - eval_2-8-451_5.txt
  - eval_2-8-451_6.txt
  - eval_2-8-451_7.txt
  - eval_2-8-451_8.txt
  - eval_2-8-451_9.txt
  cases/eval_2-8-453.yaml:
  - eval_2-8-453_0.txt
  - eval_2-8-453_1.txt
  - eval_2-8-453_2.txt
  - eval_2-8-453_3.txt
  - eval_2-8-453_4.txt
  - eval_2-8-453_5.txt
  - eval_2-8-453_6.txt
  - eval_2-8-453_7.txt
  - eval_2-8-453_8.txt
  - eval_2-8-453_9.txt
  cases/eval_2-8-459.yaml:
  - eval_2-8-459_0.txt
  - eval_2-8-459_1.txt
  - eval_2-8-459_2.txt
  - eval_2-8-459_3.txt
  - eval_2-8-459_4.txt
  - eval_2-8-459_5.txt
  - eval_2-8-459_6.txt
  - eval_2-8-459_7.txt
  - eval_2-8-459_8.txt
  - eval_2-8-459_9.txt
  cases/eval_2-8-463.yaml:
  - eval_2-8-463_0.txt
  - eval_2-8-463_1.txt
  - eval_2-8-463_2.txt
  - eval_2-8-463_3.txt
  - eval_2-8-463_4.txt
  - eval_2-8-463_5.txt
  - eval_2-8-463_6.txt
  - eval_2-8-463_7.txt
  - eval_2-8-463_8.txt
  - eval_2-8-463_9.txt
  cases/eval_2-8-464.yaml:
  - eval_2-8-464_0.txt
  - eval_2-8-464_1.txt
  - eval_2-8-464_2.txt
  - eval_2-8-464_3.txt
  - eval_2-8-464_4.txt
  - eval_2-8-464_5.txt
  - eval_2-8-464_6.txt
  - eval_2-8-464_7.txt
  - eval_2-8-464_8.txt
  - eval_2-8-464_9.txt
  cases/eval_2-8-465.yaml:
  - eval_2-8-465_0.txt
  - eval_2-8-465_1.txt
  - eval_2-8-465_2.txt
  - eval_2-8-465_3.txt
  - eval_2-8-465_4.txt
  - eval_2-8-465_5.txt
  - eval_2-8-465_6.txt
  - eval_2-8-465_7.txt
  - eval_2-8-465_8.txt
  - eval_2-8-465_9.txt
  cases/eval_2-8-466.yaml:
  - eval_2-8-466_0.txt
  - eval_2-8-466_1.txt
  - eval_2-8-466_2.txt
  - eval_2-8-466_3.txt
  - eval_2-8-466_4.txt
  - eval_2-8-466_5.txt
  - eval_2-8-466_6.txt
  - eval_2-8-466_7.txt
  - eval_2-8-466_8.txt
  - eval_2-8-466_9.txt
  cases/eval_2-8-468.yaml:
  - eval_2-8-468_0.txt
  - eval_2-8-468_1.txt
  - eval_2-8-468_2.txt
  - eval_2-8-468_3.txt
  - eval_2-8-468_4.txt
  - eval_2-8-468_5.txt
  - eval_2-8-468_6.txt
  - eval_2-8-468_7.txt
  - eval_2-8-468_8.txt
  - eval_2-8-468_9.txt
  cases/eval_2-8-469.yaml:
  - eval_2-8-469_0.txt
  - eval_2-8-469_1.txt
  - eval_2-8-469_2.txt
  - eval_2-8-469_3.txt
  - eval_2-8-469_4.txt
  - eval_2-8-469_5.txt
  - eval_2-8-469_6.txt
  - eval_2-8-469_7.txt
  - eval_2-8-469_8.txt
  - eval_2-8-469_9.txt
max_tokens: null
model_name: gpt-3.5-turbo
qa_system_prompt: You are a professional assistant for programmers. By default, questions
  and answers are in Markdown format. You are chatting with programmers, so please
  answer as briefly as possible.
sample_n: 10
system_prompt: You are a professional assistant for programmers. By default, questions
  and answers are in Markdown format.
temp: 0.2
top_p: 0.9
